// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package app is a generated GoMock package.
package app

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGoCodeParser is a mock of GoCodeParser interface.
type MockGoCodeParser struct {
	ctrl     *gomock.Controller
	recorder *MockGoCodeParserMockRecorder
}

// MockGoCodeParserMockRecorder is the mock recorder for MockGoCodeParser.
type MockGoCodeParserMockRecorder struct {
	mock *MockGoCodeParser
}

// NewMockGoCodeParser creates a new mock instance.
func NewMockGoCodeParser(ctrl *gomock.Controller) *MockGoCodeParser {
	mock := &MockGoCodeParser{ctrl: ctrl}
	mock.recorder = &MockGoCodeParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoCodeParser) EXPECT() *MockGoCodeParserMockRecorder {
	return m.recorder
}

// ParseFunctionCommentsOfGoFilesInDirectoryRecursively mocks base method.
func (m *MockGoCodeParser) ParseFunctionCommentsOfGoFilesInDirectoryRecursively(arg0 context.Context, arg1 string) (*Output, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseFunctionCommentsOfGoFilesInDirectoryRecursively", arg0, arg1)
	ret0, _ := ret[0].(*Output)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseFunctionCommentsOfGoFilesInDirectoryRecursively indicates an expected call of ParseFunctionCommentsOfGoFilesInDirectoryRecursively.
func (mr *MockGoCodeParserMockRecorder) ParseFunctionCommentsOfGoFilesInDirectoryRecursively(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseFunctionCommentsOfGoFilesInDirectoryRecursively", reflect.TypeOf((*MockGoCodeParser)(nil).ParseFunctionCommentsOfGoFilesInDirectoryRecursively), arg0, arg1)
}

// MockGherkinParser is a mock of GherkinParser interface.
type MockGherkinParser struct {
	ctrl     *gomock.Controller
	recorder *MockGherkinParserMockRecorder
}

// MockGherkinParserMockRecorder is the mock recorder for MockGherkinParser.
type MockGherkinParserMockRecorder struct {
	mock *MockGherkinParser
}

// NewMockGherkinParser creates a new mock instance.
func NewMockGherkinParser(ctrl *gomock.Controller) *MockGherkinParser {
	mock := &MockGherkinParser{ctrl: ctrl}
	mock.recorder = &MockGherkinParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGherkinParser) EXPECT() *MockGherkinParserMockRecorder {
	return m.recorder
}
